apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: globalchainx-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: globalchainx
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - path: /metrics
      port: http
      interval: 15s